# Permalinks
permalink:        pretty

# Setup
title:            Louis Dionne
tagline:          "Programming and Categories, Oh My!"
url:              http://ldionne.com
paginate:         3
baseurl:          /
author:
  name:           Louis Dionne
  url:            https://github.com/ldionne
  email:          ldionne.2@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/ldionne/ldionne.github.io
gems:             [jekyll-paginate]
